name: CI
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: sagemath/sagemath:latest
    steps:
      - name: Checkout Hodge diamond cutter
        uses: actions/checkout@v3
      - name: Run the tests in Hodge diamond cutter
        run: sage -t hodge-diamond-cutter/diamond/diamond.py
